---
abstract: 'Perl client for B<memcached>, in C language'
author:
  - 'Tomash Brechko <tomash.brechko@gmail.com>'
build_requires: {}
dynamic_config: '1'
generated_by: 'Dist::Zilla version 6.005, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cache-Memcached-Fast
requires:
  Storable: '0'
resources:
  repository: git://github.com/JRaspass/Cache-Memcached-Fast.git
version: '0.25'
